[additional_network_arguments]
learning_rate      = 3.5e-5 #2.5e-5 general.
train_text_encoder = false
text_encoder_lr    = 5e-5


[optimizer_arguments]
lr_scheduler       = "rex"
optimizer_type     = "Adopt_adv"
optimizer_args     = ["weight_decay=0.01","use_atan2=True", "cautious_mask=True", "stochastic_rounding=True","nnmf_factor=True","vector_reshape=True","cautious_wd=True" ]
min_lr             = 0

[training_arguments]
max_train_epochs    = 50
#protected_tags_file = "cleaned.txt"
loss_type          = "l2"
save_every_n_epochs = 5 
save_last_n_epochs  = 10
train_batch_size   = 16
max_grad_norm      = 1
weighted_captions  = false
seed               = 21463286
max_token_length   = 225
lowram             = false
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
save_precision     = "bf16"
mixed_precision    = "bf16"
full_bf16          = true
output_dir         = "full-epochs"
output_name        = "test-aesthetic-noAI"


[model_arguments]
pretrained_model_name_or_path = "Wheres-my-name-e1-to-e3-000001.safetensors"
vae="tools/black-forest-labs/FLUX.2-dev" #OwO
v2                    = false
sdxl                  = true
gradient_checkpointing = true
gradient_accumulation_steps = 2
sdpa                  = true
xformers              = false

[saving_arguments]
save_model_as = "safetensors"


[dataset_arguments]
cache_latents              = true
cache_latents_to_disk      = true
lr_warmup_steps            = 160
